# Generated by Django 6.0.5 on 2026-05-29 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_laborados', models.IntegerField()),
                ('horas_extras', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('sueldo_dias_trabajados', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bonos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ingreso_adicional', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('subtotal_imponible', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('decimo_tercero', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('decimo_cuarto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fondos_reserva', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('aporte_personal_iess', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('impuesto_renta', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_ingresos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_a_recibir', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'db_table': 'detalle_nomina',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=10, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('correo', models.EmailField(blank=True, max_length=150, null=True, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('area', models.CharField(max_length=100)),
                ('forma_pago', models.CharField(choices=[('transferencia', 'Transferencia'), ('efectivo', 'Efectivo')], max_length=30)),
                ('banco', models.CharField(blank=True, max_length=80, null=True)),
                ('tipo_cuenta', models.CharField(blank=True, choices=[('ahorros', 'Ahorros'), ('corriente', 'Corriente')], max_length=20, null=True)),
                ('numero_cuenta', models.CharField(blank=True, max_length=30, null=True)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('numero_iess', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('cargas_familiares', models.IntegerField(default=0)),
                ('fecha_ingreso', models.DateField()),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'empleado',
            },
        ),
        migrations.CreateModel(
            name='ImpuestoRenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField()),
                ('fraccion_basica', models.DecimalField(decimal_places=2, max_digits=12)),
                ('exceso_hasta', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('impuesto_fraccion', models.DecimalField(decimal_places=2, max_digits=12)),
                ('porcentaje_excedente', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'impuesto_renta',
                'ordering': ['anio', 'fraccion_basica'],
            },
        ),
        migrations.CreateModel(
            name='SBU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(unique=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_vigencia', models.DateField()),
            ],
            options={
                'db_table': 'sbu',
            },
        ),
        migrations.CreateModel(
            name='Descuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prestamo_hipotecario', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('prestamo_quirografario', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('prestamo_empresa', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('anticipos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('multas_atraso', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('dias_no_laborados', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('otros_descuentos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_descuentos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('detalle_nomina', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='descuento', to='nomina.detallenomina')),
            ],
            options={
                'db_table': 'descuento',
            },
        ),
        migrations.AddField(
            model_name='detallenomina',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles', to='nomina.empleado'),
        ),
        migrations.CreateModel(
            name='Nomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('tipo', models.CharField(choices=[('mensual', 'Mensual'), ('quincenal', 'Quincenal')], max_length=30)),
                ('estado', models.CharField(choices=[('generada', 'Generada'), ('aprobada', 'Aprobada'), ('pagada', 'Pagada')], default='generada', max_length=20)),
                ('fecha_generacion', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'nomina',
                'unique_together': {('anio', 'mes', 'tipo')},
            },
        ),
        migrations.AddField(
            model_name='detallenomina',
            name='nomina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='nomina.nomina'),
        ),
        migrations.AlterUniqueTogether(
            name='detallenomina',
            unique_together={('nomina', 'empleado')},
        ),
    ]
